platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

pod 'PureLayout'
pod 'YapDatabase', :git => 'https://github.com/danthorpe/YapDatabase', :branch => 'YAP-180_remove_weak_linking'
pod 'YapDatabaseExtensions', '~> 2'
pod 'TaylorSource/YapDatabase', '~> 2'
pod 'Operations/+AddressBook', :path => '../../'