platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

pod 'PureLayout'
pod 'YapDatabase', :git => 'https://github.com/yapstudios/YapDatabase', :branch => 'master'
pod 'YapDatabaseExtensions', '~> 2'
pod 'TaylorSource/YapDatabase', '~> 2'
pod 'Operations/+AddressBook', :path => '../../'