platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

pod 'PureLayout'
pod 'YapDatabaseExtensions', '~> 2'
pod 'TaylorSource/YapDatabase', '~> 2'
pod 'Operations/+AddressBook', :path => '../../'