author: Daniel Thorpe
author_url: http://danthorpe.me
module: Operations
module_version: 3.0.0
github_url: https://github.com/danthorpe/Operations
readme: README.md
podspec: Operations.podspec

swift_version: 2.2
sdk: iphoneos
xcodebuild_arguments: -scheme,Operations-iOS

exclude:
  - Tests

custom_categories:
  - name: Foundations
    children:
    - Operation
    - OperationError
    - OperationQueue
    - OperationQueueDelegate
    - OperationCondition
    - OperationConditionResult
    - OperationEvent
    - OperationObserverType        
    - OperationDidStartObserver    
    - OperationDidCancelObserver
    - OperationDidProduceOperationObserver
    - GroupOperationWillAddChildObserver    
    - OperationWillFinishObserver
    - OperationDidFinishObserver
    - StartedObserver    
    - CancelledObserver    
    - WillAddChildObserver
    - ProducedOperationObserver     
    - WillFinishObserver
    - DidFinishObserver    
    - OperationObserver    
    - LogSeverity
    - LoggerBlockType
    - LoggerType
    - OperationProfiler
    - ProfileResult
    - Queue

  - name: Building Blocks
    children:
    - GroupOperation
    - BlockOperation
    - AlertOperation
    - ComposedOperation
    - Delay    
    - DelayOperation
    - GatedOperation
    - UIOperation
    - PresentingViewController
    - ViewControllerDisplayStyle
    - MutuallyExclusive
    - NegatedCondition
    - NegatedConditionError
    - SilentCondition
    - NoFailedDependenciesCondition
    - BlockCondition
    - BlockObserver
    - BackgroundObserver
    - NetworkObserver
    - TimeoutObserver
    - Alert
    - AlertPresentation

  - name: Featured
    children:
    - ReachableOperation
    - NetworkOperation
    - WebpageOperation
    - WaitStrategy
    - RepeatedOperation
    - RepeatableOperation
    - RetryOperation
    - ResultOperationType
    - ResultOperation
    - InjectionOperationType
    - AutomaticInjectionOperationType    
    - MapOperation
    - FilterOperation
    - ReachabilityCondition
    - UserNotificationCondition
    - RemoteNotificationCondition
    - URLSessionTaskOperation
    - UserConfirmationCondition

  - name: Location 
    children:
    - LocationManagerType
    - ReverseGeocoderType
    - LocationOperationError
    - UserLocationOperation
    - _UserLocationOperation
    - ReverseGeocodeOperation
    - _ReverseGeocodeOperation
    - ReverseGeocodeUserLocationOperation
    - _ReverseGeocodeUserLocationOperation

  - name: Device Capabilities
    children:
    - CapabilityType
    - AuthorizationStatusType
    - CapabilityRegistrarType
    - Capability
    - GetAuthorizationStatus
    - Authorize
    - CapabilityError
    - AuthorizedFor

  - name: Capability.Calendar
    children:
    - Calendar
    - EventsCapabilityRegistrarType
    - EKEventStore
    - EKAuthorizationStatus
    - EventsCapability

  - name: Capability.Cloud
    children:
    - Cloud		
    - CloudContainerRegistrarType
    - CloudStatus
    - CloudCapability
    - CloudContainerRegistrar
    - CloudCapability

  - name: Capability.Health
    children:
    - Health
    - HealthCapabilityStatus
    - HealthRequirement
    - HealthCapabilityRegistrarType
    - HealthCapability

  - name: Capability.Location
    children:
    - Location
    - LocationUsage
    - LocationCapability
    - LocationCapabilityRegistrarType

  - name: Capability.Passbook
    children:
    - Passbook
    - PassbookCapability
    - PassbookCapabilityRegistrarType

  - name: Capability.Photos
    children:
    - Photos
    - PhotosCapability
    - PhotosCapabilityRegistrarType

  - name: CloudKit
    children:
    - CloudKitOperation
    - BatchedCloudKitOperation
    - CloudKitRecovery
    - OPRCKOperation
    - CKOperationType    
    - CKDatabaseOperationType    
    - CKPreviousServerChangeToken    
    - CKMoreComing
    - CKResultsLimit    
    - CKDesiredKeys
    - CKBatchedOperationType    
    - CKDiscoverAllContactsOperationType
    - CKDiscoverUserInfosOperationType
    - CKFetchNotificationChangesOperationType
    - CKFetchRecordChangesOperationType
    - CKFetchRecordZonesOperationType
    - CKFetchRecordsOperationType
    - CKFetchSubscriptionsOperationType
    - CKMarkNotificationsReadOperationType
    - CKModifyBadgeOperationType
    - CKModifyRecordZonesOperationType
    - CKModifyRecordsOperationType
    - CKModifySubscriptionsOperationType
    - CKQueryOperationType


  - name: Address Book
    children:
    - AddressBookPermissionRegistrarError
    - AddressBook
    - AddressBookAddPersonToGroup
    - AddressBookCreateGroup
    - AddressBookDisplayNewPersonViewController
    - AddressBookDisplayPersonViewController
    - AddressBookGetGroup
    - AddressBookGetResource
    - AddressBookGroup
    - AddressBookMapPeople
    - AddressBookOperation
    - AddressBookPerson
    - AddressBookRecord
    - AddressBookRemoveGroup
    - AddressBookRemovePersonFromGroup
    - AddressBookSource
    - AddressBookExternalChangeObserver
    - AddressBookGroupType
    - AddressBookPermissionRegistrar
    - AddressBookPersonType
    - AddressBookRecordType
    - AddressBookSourceType
    - AddressBookType
    - AddressBook_GroupType
    - AddressBook_PersonType
    - AddressBook_SourceType
    - AddressBookCondition
    - AddressBookReadableProperty
    - AddressBookWriteableProperty
    - StorageType
    - MultiValueRepresentable
    - PropertyType
    - ReadablePropertyType
    - WriteablePropertyType
    - LabeledValue
    - SystemAddressBookRegistrar

  - name: Contacts
    children:
    - ContactPredicate
    - ContactsError
    - ContactsPermissionError
    - ContactSaveRequestType
    - ContactStoreType
    - _ContactsCondition
    - _AddContactsToGroup
    - _ContactsAccess
    - _ContactsOperation
    - _GetContacts
    - _GetContactsGroup
    - _RemoveContactsFromGroup
    - _RemoveContactsGroup
    - DisplayContactViewController
    - DisplayCreateContactViewController
    - SystemContactStore

