steps:
  -
    name: ":bundler: Update Bundler"
    command: .scripts/update-bundler.sh
    agents:
      name: "$BUILDKITE_AGENT_META_DATA_NAME"	
  -
    name: ":fastlane: Test iOS Extension Only"
    command: .scripts/test-extension.sh
    agents:
      name: "$BUILDKITE_AGENT_META_DATA_NAME"
  -
    name: ":fastlane: Test Mac OS X"
    command: .scripts/test-osx.sh
    agents:
      name: "$BUILDKITE_AGENT_META_DATA_NAME"
  -
    name: ":fastlane: Test iOS"
    command: .scripts/test-ios.sh
    agents:
      name: "$BUILDKITE_AGENT_META_DATA_NAME"
  -
    type: "waiter"
  -
    name: ":codecov: Send Coverage"
    command: .scripts/send-coverage.sh
    agents:
      name: "$BUILDKITE_AGENT_META_DATA_NAME"
