lane :verify do
  verify_xcode  
end

lane :lint do

    swiftLint(
        mode: :lint, 
        config_file: '.swiftlint.yml'
    )
end

platform :ios do

  desc "Builds the iOS Extension compatible framework"
  lane :operations_build_extension do
    
    xcodebuild(
      project: "Operations_ExtensionCompatible.xcodeproj",
      scheme: "iOS Extensions Operations",
      xcargs: "-derivedDataPath .ci/xcodebuild-data"
    )

  end

  desc "Test the iOS Extension compatible framework"
  lane :operations_test_extension do
        
    scan(
      project: "Operations_ExtensionCompatible.xcodeproj",
      scheme: "iOS Extensions Operations",
      output_directory: ".ci/xcodebuild-data",
      xcargs: "-derivedDataPath .ci/xcodebuild-data"
    )    

  end
  
  
  desc "Runs all the tests"
  lane :operations_test do
    
    operations_test_extension()
    
    scan(
      project: "Operations.xcodeproj",
      scheme: "iOS Operations",
      output_directory: ".ci/xcodebuild-data",
      xcargs: "-derivedDataPath .ci/xcodebuild-data"
    )
    
    slather(
	    proj: "Operations.xcodeproj",
    	scheme: "iOS Operations",
    	build_directory: ".ci/xcodebuild-data",
    	use_bundle_exec: true    	
    )
	
  end
  
  desc "iOS: ProcedureKit"
  lane :test do

    scan(
      project: "ProcedureKit.xcodeproj",
      scheme: "ProcedureKit",
      destination: "platform=iOS"
    )
  end

  desc "iOS: ProcedureKitMobile"
  lane :test_mobile do

    scan(
      project: "ProcedureKit.xcodeproj",
      scheme: "ProcedureKitMobile",
      destination: "platform=iOS"
    )
  end

  desc "iOS: ProcedureKitCloud"
  lane :test_cloud do

    scan(
      project: "ProcedureKit.xcodeproj",
      scheme: "ProcedureKitCloud",
      destination: "platform=iOS"
    )
  end



end

platform :mac do

  desc "Operations: Builds the OS X Extension compatible framework"
  lane :operations_build_extension do
    
    xcodebuild(
      project: "Operations_ExtensionCompatible.xcodeproj",
      scheme: "OS X Extensions Operations",
      xcargs: "-derivedDataPath .ci/xcodebuild-data"
    )

  end
  
  desc "Operations: Test the OS X Extension compatible framework"
  lane :operations_test_extension do
        
    scan(
      project: "Operations_ExtensionCompatible.xcodeproj",
      scheme: "OS X Extensions Operations",
      output_directory: ".ci/xcodebuild-data",
      derived_data_path: ".ci/xcodebuild-data"
    )    

  end  

  desc "Operations: Runs all the tests"
  lane :operations_test do

	operations_test_extension()

    scan(
      project: "Operations.xcodeproj",
      scheme: "OS X Operations",
      output_directory: ".ci/xcodebuild-data",
      derived_data_path: ".ci/xcodebuild-data"
    )

  end
  
  desc "macOS: ProcedureKit"
  lane :test do

    scan(
      project: "ProcedureKit.xcodeproj",
      scheme: "ProcedureKit",
      destination: "platform=OS X"
    )
  end

  desc "macOS: ProcedureKitMac"
  lane :test_mac do

    scan(
      project: "ProcedureKit.xcodeproj",
      scheme: "ProcedureKitMac",
      destination: "platform=OS X"
    )
  end

  desc "macOS: ProcedureKitCloud"
  lane :test_cloud do

    scan(
      project: "ProcedureKit.xcodeproj",
      scheme: "ProcedureKitCloud",
      destination: "platform=OS X"
    )
  end

  
end