default_platform :ios

platform :ios do

  desc "Runs all the tests"
  lane :test do
	xctest 	scheme: 'Operations', 
			sdk: 'iphonesimulator', 
			destination: 'platform=iOS Simulator,name=iPhone 6,OS=8.4',
			derivedDataPath: '.fastlane/xcodebuild-data'
  end
end
