#!/usr/bin/env bash
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby ruby
bundle exec slather coverage --scheme "iOS Operations" --buildkite --coveralls --build-directory .ci/xcodebuild-data