#!/usr/bin/env bash
set -o pipefail
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby ruby
bundle install --quiet
xcodebuild -project "ProcedureKit.xcodeproj" -scheme "Stress Tests" -destination "platform=macOS" clean test | tee .ci/results/xcodebuild.log | xcpretty