#!/usr/bin/env bash
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby ruby
bundle install --quiet && bundle exec fastlane ios test
bash <(curl -s https://codecov.io/bash) -D .ci/xcodebuild-data
