#!/usr/bin/env bash
set -euo pipefail
set +u
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby ruby
set -u

echo "cd Integrations/SPM"
cd "Integrations/SPM"

echo "--- SPM update"
swift package update

echo "--- swift build"
swift build

echo "--- swift test"
swift test
