#!/usr/bin/env bash
set -o pipefail
source /usr/local/opt/chruby/share/chruby/chruby.sh
chruby ruby
bundle install --quiet
xcodebuild -project "ProcedureKit.xcodeproj" -scheme "iOS" -destination "platform=iOS Simulator,name=iPhone X" clean test | tee xcodebuild.log | xcpretty